apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: green-svc
  namespace: udacity
spec:
  ports:
  - nodePort: 31063
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: green
  type: LoadBalancer